{{- /*
.Files.Get "files/LICENSE"
*/}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-k8s-encryption
subjects:
  - kind: ServiceAccount
    name: cray-k8s-encryption
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cray-k8s-encryption
  apiGroup: rbac.authorization.k8s.io
