{{- /*
.Files.Get "files/LICENSE"
*/}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-k8s-encryption
rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    - secrets
    - daemonsets
    verbs:
    - get
    - list
    - create
    - delete
    - patch
    - update
